# Generated by Django 3.1.1 on 2020-10-08 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="img_url",
            field=models.CharField(
                default="", max_length=100, verbose_name="imague url"
            ),
            preserve_default=False,
        ),
    ]
