# Generated by Django 3.1.1 on 2020-10-21 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0004_recipe_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="category",
            field=models.TextField(
                choices=[
                    ("breakfast", "BREAKFAST"),
                    ("lunch", "LUNCH"),
                    ("dinner", "DINNER"),
                    ("dessert", "DESSERT"),
                    ("drink", "DRINK"),
                ],
                default="DESSERT",
                verbose_name="category",
            ),
        ),
    ]
