# Generated by Django 3.1.2 on 2020-10-29 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0005_auto_20201021_0323"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="category",
            field=models.TextField(
                choices=[
                    ("breakfast", "BREAKFAST"),
                    ("lunch", "LUNCH"),
                    ("dinner", "DINNER"),
                    ("side", "SIDE"),
                    ("dessert", "DESSERT"),
                    ("drink", "DRINK"),
                ],
                default="dessert",
                verbose_name="category",
            ),
        ),
    ]
