# Generated by Django 3.1.2 on 2020-10-31 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0006_auto_20201029_1657"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="image",
            field=models.ImageField(default="mwccc.jpg", upload_to="images"),
            preserve_default=False,
        ),
    ]
